### ISSUE TITLE
Inconsistency in using recommended terms

### ISSUE THREAD

**Issue by adregan** [modernxmpp/modernxmpp#46]
Hello! A nit pick/question here:

I first read the [terminology](https://docs.modernxmpp.org/terminology/#terminology) section to familiarize myself with some of the terms, and I was very pleased that the recommended terms were offered (and they appear to be much nicer than the historic terms).

However, the next page I visited was the [user interface guidelines](https://docs.modernxmpp.org/client/design/#account) and I was immediately confronted with the historical term `JID` rather than the recommended `Address`. 

I assume the historic terms will be tough to excise from conversation, but was wondering if this inconsistency was intentional in the guidelines or if the terms should be replaced with their recommended versions.

**Comment by mwild1** [comment]
Hi! This is indeed a sensible question to ask. There was previously discussion about it here: https://github.com/modernxmpp/modernxmpp/pull/23#issuecomment-542787811

The conclusion was that we'll keep the technical terms in the documentation (which is aimed at developers). Otherwise it has the potential to get too confusing.

It may be worth us documenting this decision, so I'll keep this issue open for now.

**Comment by mwild1** [comment]
I've added some wording about this in commit https://github.com/modernxmpp/modernxmpp/commit/5ca1c6d5883fbf81c73e70d496f5faa4cc9eb3c7 :+1:
